name: todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  custom_lint:
  json_serializable: ^6.8.0
  test: ^1.25.15
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
